<a href="https://colab.research.google.com/github/ruanwensheng/Machine-Learning-Algorithms-/blob/tensorflow/tensorflow.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [6]:
pip install tensorflow

In [7]:
%tensorflow_version 2.x

Colab only includes TensorFlow 2.x; %tensorflow_version has no effect.


In [8]:
import tensorflow as tf

x = tf.Variable(3, name = "x")
y = tf.Variable(4, name = "y")

f = x*x*y + y + 2
f

<tf.Tensor: shape=(), dtype=int32, numpy=42>

Tensorflow has 2 main components:

- **Session**: like an environment allowing parts of the graph to be executed. allocates memory, handle execution of operations, computations defined

- **Graph**: Nothing is computed or stored in this graph, simply a way to define the operations that have written in the code



**TENSOR**
- a generalization of vectors and matrices to higher dimensions.
- TF represents tensors as n-dim arrays of base datatypes.

- they are main objects that are passed around, manipulated throughout the program.

Tensor = dữ liệu + hình dạng (shape) + kiểu dữ liệu (dtype).

dtype: float32, int32, string ,...

In [9]:
# creating a tensor tf.Variable(...)

string = tf.Variable("this is a string", tf.string)
number = tf.Variable(10, tf.int16)
floating = tf.Variable(3.56, tf.float64)

**Rank/Degree of Tensor**

Rank = số chiều (number of dimensions / axes) của tensor, không liên quan gì tới “rank” trong đại số tuyến tính.

Ví dụ:

Scalar: rank = 0 → không có chiều (chỉ là 1 giá trị).
**tf.constant(5) → rank 0**

Vector: rank = 1 → có 1 chiều.
**tf.constant([1,2,3]) → rank 1**

Matrix: rank = 2 → có 2 chiều (hàng, cột).
**tf.constant([[1,2],[3,4]]) → rank 2**

3D tensor: rank = 3 → thường dùng cho ảnh màu (height, width, channels).

In [10]:
import tensorflow as tf

t1 = tf.constant(5)                      # rank 0
t2 = tf.constant([1, 2, 3])               # rank 1
t3 = tf.constant([[1, 2], [3, 4]])        # rank 2

print(tf.rank(t1).numpy())  # 0
print(tf.rank(t2).numpy())  # 1
print(tf.rank(t3).numpy())  # 2


0
1
2


**Shape**
- the shape of a tensor is the amount of elements in each dim

In [16]:
t3.shape

TensorShape([2, 2])

**Changing shape**


In [25]:
# tf.ones(...) tạo ra cái shape [1,2,3] toàn số 1
tensor1 = tf.ones([2,2,3])
print(tensor1)

tensor2 = tf.reshape(tensor1, [1,6,2])
print(tensor2)

tf.Tensor(
[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]], shape=(2, 2, 3), dtype=float32)
tf.Tensor(
[[[1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]]], shape=(1, 6, 2), dtype=float32)


Type of Tensors
- Variable
- Constant
- Placeholder
- Sparse Tensor

except for variable, all others are immutable